# Generated by Django 3.0.3 on 2020-08-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='file',
            new_name='download',
        ),
    ]
