# Generated by Django 3.0.3 on 2020-09-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200821_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='media/courses/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(max_length=300, upload_to='course/resourse/%Y/%m', verbose_name='下载地址'),
        ),
    ]
