# Generated by Django 3.0.3 on 2020-09-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200821_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imag',
            field=models.ImageField(default='default.jpg', upload_to='media/head_imag/%Y/%m', verbose_name='用户头像'),
        ),
    ]
