# Generated by Django 3.0.3 on 2020-09-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200825_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='Image',
            field=models.ImageField(upload_to='media/org/%Y/%m', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='imag',
            field=models.ImageField(upload_to='media/teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
